---
title: "PCA on Paul and Nestorowa (Gene Exp) Data"
author: "Michelle Li"
date: "6/28/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(rgl)
knit_hooks$set(webgl = hook_webgl)
```

----

## Handwritten PCA 

This is the handwritten version of PCA in R, I used SVD for everything (not eig).

## Paul Data

```{r paul, echo=FALSE}
# IMPORTANT NOTE ON DIMENSIONS:
# whatever you want plotted in PCA, whether the cells or the genes, put that in the COLUMNS of your data matrix
# e.g. to get PCA that plots for each CELL, make sure you have cells as columns, genes as rows
# nestorowa data: 1645 cells, 4290 genes. 1645 x 4290. want to use transpose
# for Paul data: use regular data matrix (genes x cells)

## load data 
load("/Users/Michelle/Downloads/data_Paul_Cell2015/Paul_Cell_MARSseq_GSE72857.RData")
dataname <- "Paul Data" # enter title of data
X <- data

## create factor for grouping
groupsf <- factor(cluster.id) # paul data
nclusters <- nlevels(groupsf) # number of groups to cluster
colors <- rainbow(nclusters) # choose colors

## center data
M1centered <- scale(X, center=TRUE, scale=FALSE) # subtracts column means from each column

## svd
svd <- svd(M1centered, nu=3, nv=0)
U <- svd$u # dim: nrowx3

## calculate scores
scores <- t(M1centered) %*% U # columns of scores are the principal components, dim: ncolx3
```

2D plot of scores
```{r plot2dscores-paul, echo=FALSE}
plot(x=scores[,1], y=scores[,2], xlab="PC1 scores", ylab="PC2 scores", col = colors[groupsf], pch=20, main = paste("PCA Scores (Handwritten),", dataname))
legend("bottomright", inset = c(0,0), legend = levels(groupsf), pch = 20, col = colors, ncol=3, cex=0.4)
```

3D plot of scores
```{r plot3dscores-paul, echo=FALSE, webgl=TRUE}
open3d()
plot3d(x=scores[,1], y=scores[,2], z=scores[,3], xlab="PC1 scores", ylab="PC2 scores", zlab="PC3 scores", col = colors[groupsf], pch=20, main = paste("PCA Scores (Handwritten),", dataname))
par3d(windowRect=c(20,30,1000,1000))
legend3d("bottomright", legend = levels(groupsf), inset=c(0.2,0.2), pch = 20, col = colors, ncol=3, cex=1)
```

2D plot of PCs (eigenvectors of actual cov matrix)
```{r plot2dpcs-paul, echo=FALSE}
## plot PCs 2d (eigenvectors of original covariance matrix)
plot(x=U[,1], y=U[,2], xlab="PC1", ylab="PC2", col = colors[groupsf], pch=20, main = paste("PCA (Handwritten),", dataname))
legend("bottomleft", inset = c(0,0), legend = levels(groupsf), pch = 20, col = colors, ncol=3, cex=0.4)
```

3D plot of PCs (eigenvectors of actual cov matrix)
```{r plot3dpcs-paul, echo=FALSE, webgl=TRUE}
## plot PCs 3d
open3d()
plot3d(x=U[,1], y=U[,2], z=U[,3], xlab="PC1", ylab="PC2", zlab="PC3", col = colors[groupsf], pch=20, main = paste("PCA (Handwritten),", dataname))
par3d(windowRect=c(20,30,1000,1000))
legend3d("bottomright", legend = levels(groupsf), inset=c(0.2,0.2), pch = 20, col = colors, ncol=3, cex=1)
```


## Nestorowa Data

```{r nestorowa, echo=FALSE}
coordinates_gene_counts_flow_cytometry <- read.delim("~/Downloads/coordinates_gene_counts_flow_cytometry.txt", row.names=1)
rawdata <- coordinates_gene_counts_flow_cytometry
cleandata <- na.omit(rawdata) # remove rows with NA
data <- cleandata[,14:ncol(cleandata)] # choose relevant flow cytometry data
data <- as.matrix(data)
X <- data
dataname <- "Nestorowa Data"

# create factor for grouping
rownames <- row.names(data)
groups <- as.character(rownames)
groups[grepl("HSPC",groups)] <- "HSPC" # replace all labels with hspc
groups[grepl("LT",groups)] <- "LT.HSC" # replace with lt.hsc
groups[grepl("Prog",groups)] <- "PROG" # same for prog
groupsf <- factor(groups)
nclusters <- nlevels(groupsf) # number of groups to cluster
colors <- rainbow(nclusters) # choose colors

## center data
M1centered <- scale(X, center=TRUE, scale=FALSE) # subtracts column means from each column

## svd
svd <- svd(M1centered, nu=3, nv=0)
U <- svd$u # dim: nrowx3

## calculate scores
scores <- t(M1centered) %*% U # columns of scores are the principal components, dim: ncolx3
```

2D plot of scores 
```{r plot2dscores-nestorowa, echo=FALSE}
plot(x=scores[,1], y=scores[,2], xlab="PC1 scores", ylab="PC2 scores", col = colors[groupsf], pch=20, main = paste("PCA Scores (Handwritten),", dataname))
legend("bottomright", inset = c(0,0), legend = levels(groupsf), pch = 20, col = colors, ncol=1, cex=0.4)
```

3D plot of scores 
```{r plot3dscores-nestorowa, echo=FALSE, webgl=TRUE}
## plot scores 3d
open3d()
plot3d(x=scores[,1], y=scores[,2], z=scores[,3], xlab="PC1 scores", ylab="PC2 scores", zlab="PC3 scores", col = colors[groupsf], pch=20, main = paste("PCA Scores (Handwritten),", dataname))
par3d(windowRect=c(20,30,1000,1000))
legend3d("bottomright", legend = levels(groupsf), inset=c(0.2,0.2), pch = 20, col = colors, ncol=1, cex=1)
```

2D plot of PCs
```{r plot2dpcs-nestorowa, echo=FALSE}
## plot PCs 2d (eigenvectors of original covariance matrix)
plot(x=U[,1], y=U[,2], xlab="PC1", ylab="PC2", col = colors[groupsf], pch=20, main = paste("PCA (Handwritten),", dataname))
legend("topright", inset = c(0,0), legend = levels(groupsf), pch = 20, col = colors, ncol=1, cex=0.4)
```

3D plot of PCs
```{r plot3d-pcs-nestorowa, echo=FALSE, webgl=TRUE}
## plot PCs 3d
open3d()
plot3d(x=U[,1], y=U[,2], z=U[,3], xlab="PC1", ylab="PC2", zlab="PC3", col = colors[groupsf], pch=20, main = paste("PCA (Handwritten),", dataname))
par3d(windowRect=c(20,30,1000,1000))
legend3d("bottomright", legend = levels(groupsf), inset=c(0.2,0.2), pch = 20, col = colors, ncol=1, cex=1)
```


