---
title: "Paul Gene Expression Data: Dimension Reduction"
author: "Michelle Li and Gianna Wu with Professor de Pillis and Dr. Park"
date: "7/2/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(destiny)
library(Biobase)
library(tsne)
library(rgl)
options(rgl.useNULL = TRUE)
r3dDefaults$windowRect <- c(0,0,1000,1000)
```

```{r load-paul, include=FALSE}
## load .Rdata file into environment so you have all calculations done
## if you have the .RData file to load, use eval=FALSE for pca, diffmap, tsne
load("~/GitHub/cell-diff-reu-2018/paul-rmd-data.RData")
```

----

Analyzing Paul gene expression data using the following dimension reduction techniques in R: PCA (handwritten version), diffusion mapping (destiny package), and t-SNE (tsne package). The original Paul data comes in as a matrix of 8716 genes x 2730 cells.  

## PCA (Handwritten)

```{r pca-paul, eval=FALSE, include=FALSE}
## load data 
load("~/GitHub/cell-diff-reu-2018/data/Paul_Cell_MARSseq_GSE72857.RData")
dataname <- "Paul Gene Expression Data" # enter title of data

## create factor for grouping
groupsf <- factor(cluster.id) # paul data
nclusters <- nlevels(groupsf) # number of groups to cluster
colors <- rainbow(nclusters) # choose colors

gclusters <- nlevels(info.genes)
gcolors <- rainbow(gclusters)

# IMPORTANT NOTE ON DIMENSIONS:
# whatever you want plotted in PCA, whether the cells or the genes, put that in the COLUMNS of your data matrix
# e.g. to get PCA that plots for each CELL, make sure you have cells as columns, genes as rows
# for Paul data: use regular data matrix (genes x cells)

## center data
M1centered <- scale(data, center=TRUE, scale=FALSE) # subtracts column means from each column

## svd
svd <- svd(M1centered, nu=3, nv=3)
U <- svd$u # dim: nrowx3
V <- svd$v 
# Note: U = M1centered %*% V %*% S^-1

## calculate weights
weights <- t(M1centered) %*% U # columns of weights are weights, dim: ncolx3
scores <- M1centered %*% V # basically U 
```

#### Plots of weights 
Weights were calculated by doing: weights = t(M1centered) %*% U, where M1centered is the centered data and U contains the left singular vectors from SVD. 

2D plot of weights   
```{r pca-plot2dweights}
plot(x=weights[,1], y=weights[,2], 
     xlab="PC1 weights", ylab="PC2 weights", 
     col = colors[groupsf], 
     pch=20, 
     main = paste("PCA Weights (Handwritten),", dataname))
legend("bottomright", inset = c(0,0), 
       legend = levels(groupsf), 
       pch = 20, 
       col = colors, 
       ncol=3, cex=0.4)
```

3D plot of weights 
```{r pca-plot3dweights}
plot3d(x=weights[,1], y=weights[,2], z=weights[,3], 
       xlab="PC1 weights", ylab="PC2 weights", zlab="PC3 weights", 
       col = colors[groupsf], 
       pch=20, 
       main = paste("PCA Weights (Handwritten),", dataname))
legend3d("bottomright", inset=c(0.1,0.1),
         legend = levels(groupsf), 
         pch = 20, 
         col = colors, 
         ncol=3, cex=1.5)
rglwidget()
```

#### Plots of principal components

2D plot of PCs (eigenvectors of actual covariance matrix)  
```{r pca-plot2dpcs}
## plot PCs 2d (eigenvectors of original covariance matrix)
plot(x=U[,1], y=U[,2], 
     xlab="PC1", ylab="PC2", 
     col = colors[groupsf], 
     pch=20, 
     main = paste("PCA (Handwritten),", dataname))
legend("bottomleft", inset = c(0,0),
       legend = levels(groupsf),
       pch = 20,
       col = colors,
       ncol=3, cex=0.4)
```

3D plot of PCs (eigenvectors of actual covariance matrix)  
```{r pca-plot3dpcs}
## plot PCs 3d
plot3d(x=U[,1], y=U[,2], z=U[,3], 
       xlab="PC1", ylab="PC2", zlab="PC3", 
       col = colors[groupsf], 
       pch=20, 
       main = paste("PCA (Handwritten),", dataname))
legend3d("bottomright", inset=c(0.1,0.1),
         legend = levels(groupsf),
         pch = 20, 
         col = colors, 
         ncol=3, cex=1.5)
rglwidget()
```



2D plot of PCs (eigenvectors of actual covariance matrix)  
```{r pca-plot2dpcs-gradient}
geneexp1 <- factor(data[,1])
geneexp300 <- factor(data[,300])
## plot PCs 2d (eigenvectors of original covariance matrix)
plot(x=U[,1], y=U[,2], 
     xlab="PC1", ylab="PC2", 
     col = rainbow(nlevels(geneexp300))[geneexp300],
     pch = 20, 
     main = paste("PCA (Handwritten),", dataname))
legend("bottomright", inset = c(0,0),
       legend = levels(geneexp2),
       pch = 20,
       col = colors,
       ncol=3, cex=0.4)
```


----

## Diffusion Mapping (destiny)

Diffusion mapping using destiny package.  
```{r diffmap-paul, eval=FALSE, include=FALSE}
## previously read in data and converted to matrix 
## convert to expression set
## NOTE ON EXPRESSION SET DIMENSIONS: cells = columns ; genes = rows
## Paul does NOT need to transpose data
dataES <- ExpressionSet(assayData=data) # you must include the 'assayData=' for this to come out correctly

## diffusion map (un-normalized data)
dm <- DiffusionMap(dataES)

## sigmas
sigmas <- find_sigmas(dataES) 
```

2D Diffusion Map  
```{r diffmap-plot2d}
## plot 2d
plot(x=eigenvectors(dm)[,1], y=eigenvectors(dm)[,2],
     xlab="DC1", ylab="DC2",
     col = colors[groupsf],
     pch=20, 
     main = paste("Diffusion Map (destiny),", dataname))
legend("bottomright", inset=c(0,0), 
       legend=levels(groupsf), 
       col=colors, 
       pch=20, 
       ncol=3, cex=0.3) 
```

3D Diffusion Map  
```{r diffmap-plot3d}
## plot 3d
plot3d(x=eigenvectors(dm)[,1], y=eigenvectors(dm)[,2], z=eigenvectors(dm)[,3],
       xlab="DC1", ylab="DC2", zlab="DC3",
       col = colors[groupsf],
       pch=20, 
       main = paste("Diffusion Map (destiny) of", dataname))
legend3d("bottomright", inset=c(0.1,0.1),
         legend = levels(groupsf),
         pch = 20, 
         col = colors, 
         ncol=3, cex=1.5)
rglwidget()
```

Sigmas  
```{r diffmap-sigmas}
plot(sigmas)
```

----

## t-SNE (tsne package)

t-SNE using tsne package (from jdonaldson, linked on van der Maaten's website).

```{r tsne-paul, eval=FALSE, include=FALSE}
## already read in data and converted to matrix
# Note: can take very, very long with large datasets, such as Paul
# t-SNE DIMENSIONS: rows=cells, columns=genes
# Paul data needs transpose to have correct dimensions

ydata1 <- tsne(t(data), k=3, max_iter = 200, perplexity = 50) # ydata = matrix(rnorm(k * n),n) 
```

2D t-SNE plot  
```{r tsne-plot2d}
plot(x=ydata3d[,1], y=ydata3d[,2], 
     col = colors[groupsf], 
     pch=20,
     main = paste("2D t-SNE Plot of", dataname, "(tsne)")) 
legend("bottomleft", inset = c(0,0), 
       legend = levels(groupsf), 
       pch = 20, 
       col = colors, 
       ncol=3, cex=0.3) 
```

3D t-SNE plot  
```{r tsne-plot3d}
plot3d(x=ydata3d[,1], y=ydata3d[,2], z=ydata3d[,3], 
       col=colors[groupsf], 
       pch=20,
       main = paste("3D t-SNE Plot of", dataname, "(tsne)"))
legend3d("bottomright", inset=c(0.1,0.1),
         legend = levels(groupsf),  
         pch = 20, 
         col = colors, 
         ncol=3, cex=1.5)
rglwidget()
```


2D t-SNE plot highlighting selected cluster

 
```{r tsne-select}
clusterindex <- 10 # select index of the cluster you want to visualize
color1 <- colors
color1[-clusterindex] <- "black"
```

```{r tsne-plot2d-select}
plot(x=ydata3d[,1], y=ydata3d[,2], 
     col = color1[groupsf], 
     pch=20,
     main = paste("2D t-SNE Plot of Cluster", clusterindex, dataname, "(tsne)")) 
legend("bottomleft", inset = c(0,0), 
       legend = levels(groupsf), 
       pch = 20, 
       col = color1, 
       ncol=3, cex=0.3) 
```

3D t-SNE plot highlighting selected cluster  
```{r tsne-plot3d}
plot3d(x=ydata3d[,1], y=ydata3d[,2], z=ydata3d[,3], 
       col = color1[groupsf],
       pch=20,
       main = paste("3D t-SNE Plot of Cluster", clusterindex, dataname, "(tsne)"))
rglwidget()
```
